#!/bin/tclsh
import os
tmpdir = os.getenv('TMP') or (os.getcwd() + '/TMP')

print("SETTING CONFIGURATION")
dbset('db','firebird')
dbset('bm','TPC-C')

diset('connection','fb_host','localhost')
diset('connection','fb_port','3050')
diset('connection','fb_odbc_driver','Firebird ODBC Driver')
diset('connection','fb_charset','UTF8')
diset('connection','fb_embedded','true')

diset('tpcc','fb_user','SYSDBA')
diset('tpcc','fb_pass','masterkey')
diset('tpcc','fb_dbase', tmpdir + '/tpcc.fdb')
diset('tpcc','fb_driver','timed')
diset('tpcc','fb_total_iterations','10000000')
diset('tpcc','fb_rampup','2')
diset('tpcc','fb_duration','5')
diset('tpcc','fb_allwarehouse','true')
diset('tpcc','fb_timeprofile','true')

loadscript()
print("TEST STARTED")
vuset('vu','vcpu')
vucreate()
tcstart()
tcstatus()
jobid = tclpy.eval('vurun')
vudestroy()
tcstop()
print("TEST COMPLETE")
file_path = os.path.join(tmpdir, "fb_tprocc")
fd = open(file_path, "w")
fd.write(jobid)
fd.close()
exit()
