SET TERM ^ ;

CREATE OR ALTER PROCEDURE PAYMENT_SP (
    P_W_ID    INTEGER,
    P_D_ID    SMALLINT,
    P_C_W_ID  INTEGER,
    P_C_D_ID  SMALLINT,
    P_C_ID    INTEGER,
    P_AMOUNT  NUMERIC(12,2),
    P_DATE    TIMESTAMP)
RETURNS (
    OUT_C_BALANCE NUMERIC(12,2),
    OUT_C_CREDIT  CHAR(2),
    OUT_W_NAME    VARCHAR(10),
    OUT_D_NAME    VARCHAR(10))
AS
DECLARE VARIABLE H_DATA VARCHAR(24);
BEGIN
    UPDATE WAREHOUSE
        SET W_YTD = W_YTD + :P_AMOUNT
        WHERE W_ID = :P_W_ID
        RETURNING W_NAME INTO :OUT_W_NAME;

    UPDATE DISTRICT
        SET D_YTD = D_YTD + :P_AMOUNT
        WHERE D_W_ID = :P_W_ID AND D_ID = :P_D_ID
        RETURNING D_NAME INTO :OUT_D_NAME;

    SELECT C_BALANCE, C_CREDIT FROM CUSTOMER
        WHERE C_W_ID = :P_C_W_ID
          AND C_D_ID = :P_C_D_ID
          AND C_ID   = :P_C_ID
        INTO :OUT_C_BALANCE, :OUT_C_CREDIT;

    OUT_C_BALANCE = OUT_C_BALANCE - :P_AMOUNT;

    UPDATE CUSTOMER
        SET C_BALANCE     = :OUT_C_BALANCE,
            C_YTD_PAYMENT = C_YTD_PAYMENT + :P_AMOUNT,
            C_PAYMENT_CNT = C_PAYMENT_CNT + 1
        WHERE C_W_ID = :P_C_W_ID
          AND C_D_ID = :P_C_D_ID
          AND C_ID   = :P_C_ID;

    H_DATA = :OUT_W_NAME || '    ' || :OUT_D_NAME;
    INSERT INTO HISTORY
        (H_C_ID, H_C_D_ID, H_C_W_ID, H_W_ID, H_D_ID,
         H_DATE, H_AMOUNT, H_DATA)
    VALUES (:P_C_ID, :P_C_D_ID, :P_C_W_ID, :P_W_ID, :P_D_ID,
            :P_DATE, :P_AMOUNT, :H_DATA);

    SUSPEND;
END
^

SET TERM ; ^

COMMIT;
